name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
      runs=on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - run: npm ci
        - run: npm run build
        - uses: actions/upload artifact@v3
          with:
            path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/deploy-pages@v4
